apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: techpreview-capacity-planning.rules
  namespace: openshift-monitoring
spec:
  groups:
  - name: techpreview-capacity-planning.rules
    rules:
    - expr: ( rate(ceph_cluster_total_used_bytes[30d]) )
      record: odf_rate_consumption
    - expr: ( ( ceph_cluster_total_bytes - ceph_cluster_total_used_bytes  ) / (rate(ceph_cluster_total_used_bytes[30d]) ) )
      record: odf_time_until_exhaustion
    - expr: ( predict_linear( ceph_cluster_total_used_bytes[15m], 300) )
      record: odf_used_capacity_forecast
